-- 0007_seed_projects.sql
-- 12 örnek proje. Görsel placeholder'ları public/images/ altında SVG.

insert into public.projects (slug, title, type, location, capacity_kwp, cover_image, description, before_image, after_image, gallery_images, product_slugs, customer_quote, customer_name, annual_savings_try, completion_date, sort_order)
values
-- Konut (4)
('antalya-villa', 'Antalya Villa Çatı GES', 'konut', 'Antalya / Konyaaltı', 12, '/images/placeholder-project-1.svg',
 'Akdeniz iklimine uygun olarak tasarlanan 12 kWp gücünde monokristal panel sistemi. Yıllık ortalama 18.500 kWh üretimle ailenin elektrik faturasının %92''sini karşılıyor.',
 '/images/placeholder-project-1-before.svg', '/images/placeholder-project-1-after.svg',
 array['/images/placeholder-project-1-1.svg','/images/placeholder-project-1-2.svg','/images/placeholder-project-1-3.svg'],
 array[]::text[],
 'Yatırımımız 4 yılda kendini ödedi, üstüne komşulara da örnek olduk.', 'M. Demir', 38500, '2024-08-15', 10),
('istanbul-cati', 'İstanbul Çatı GES', 'konut', 'İstanbul / Beykoz', 15, '/images/placeholder-project-4.svg',
 '15 kWp''lik konut sistemi, kuzey Anadolu''nun bulutlu günleri düşünülerek yüksek verimli panellerle kurgulandı. Akıllı izleme paneli ile telefondan üretim takip ediliyor.',
 null, null,
 array['/images/placeholder-project-4-1.svg','/images/placeholder-project-4-2.svg'],
 array[]::text[],
 'Mobil uygulamadan üretimi izlemek inanılmaz keyifli.', 'A. Yılmaz', 47000, '2024-11-02', 20),
('ankara-mustakil', 'Ankara Müstakil Ev', 'konut', 'Ankara / Çankaya', 8, '/images/placeholder-project-7.svg',
 '8 kWp paket sistem, geleneksel kiremit çatı üzerine alüminyum montaj sistemi ile uygulandı. Mahsuplaşma yöntemiyle yıllık fatura ortalama 6.800 TL''den 1.200 TL''ye indi.',
 '/images/placeholder-project-7-before.svg', '/images/placeholder-project-7-after.svg',
 array['/images/placeholder-project-7-1.svg'],
 array[]::text[],
 null, null, 22000, '2025-01-10', 30),
('izmir-villa', 'İzmir Villa Sistem', 'konut', 'İzmir / Karşıyaka', 10, '/images/placeholder-project-8.svg',
 '10 kWp hibrit sistem, batarya destekli. Şebeke kesilse bile kritik tüketim (buzdolabı, aydınlatma, internet) batarya üzerinden devam ediyor.',
 null, null,
 array['/images/placeholder-project-8-1.svg','/images/placeholder-project-8-2.svg'],
 array[]::text[],
 'Yaz aylarında haftada 1-2 gün kesinti yaşıyorduk, artık sıfır.', 'E. Kaya', 32000, '2025-02-22', 40),

-- Ticari (4)
('konya-fabrika', 'Konya Mobilya Fabrikası', 'ticari', 'Konya / Selçuklu', 250, '/images/placeholder-project-2.svg',
 '250 kWp''lik fabrika çatı GES. Üretim hattının gündüz tüketimini neredeyse tamamen karşılıyor. KDV %1 avantajıyla geri ödeme süresi 3.5 yıla indi.',
 '/images/placeholder-project-2-before.svg', '/images/placeholder-project-2-after.svg',
 array['/images/placeholder-project-2-1.svg','/images/placeholder-project-2-2.svg','/images/placeholder-project-2-3.svg'],
 array[]::text[],
 'Aylık enerji giderimiz 180.000 TL''den 35.000 TL''ye düştü.', 'Mobilya A.Ş.', 1740000, '2024-06-30', 50),
('kayseri-otel', 'Kayseri Termal Otel', 'ticari', 'Kayseri / Kocasinan', 180, '/images/placeholder-project-5.svg',
 '180 kWp otel projesi. Gündüz havuz/iklimlendirme yükü güneşten karşılanıyor. Yatırım teşvik belgesi ile %50 vergi indirimi alındı.',
 null, null,
 array['/images/placeholder-project-5-1.svg','/images/placeholder-project-5-2.svg'],
 array[]::text[],
 null, null, 1240000, '2024-09-12', 60),
('bursa-market', 'Bursa Süpermarket Zinciri', 'ticari', 'Bursa / Nilüfer', 90, '/images/placeholder-project-9.svg',
 '90 kWp süpermarket çatı GES. Soğutma reyonlarının yüksek elektrik tüketimi gündüz güneşle dengeleniyor. Kuzey-güney çift yönlü panel yerleşimi ile alan optimize edildi.',
 null, null,
 array['/images/placeholder-project-9-1.svg'],
 array[]::text[],
 'Yatırımı 4 yılda geri kazanıyoruz; süpermarket zinciri tüm şubelere yaygınlaştırma kararı aldı.', 'Bursa Market Zinciri', 620000, '2024-12-05', 70),
('eskisehir-depo', 'Eskişehir Lojistik Depo', 'ticari', 'Eskişehir / Tepebaşı', 320, '/images/placeholder-project-10.svg',
 '320 kWp lojistik depo çatı GES. Yüksek tavanlı çelik konstrüksiyona özel ankraj çözümü ile uygulandı. Artan elektrik şebekeye satılarak ekstra gelir sağlanıyor.',
 '/images/placeholder-project-10-before.svg', '/images/placeholder-project-10-after.svg',
 array['/images/placeholder-project-10-1.svg','/images/placeholder-project-10-2.svg'],
 array[]::text[],
 null, null, 2200000, '2025-03-18', 80),

-- Tarım (4)
('aydin-sera', 'Aydın Sera Sulama', 'tarim', 'Aydın / Söke', 30, '/images/placeholder-project-3.svg',
 '30 kWp tarımsal sulama GES. Damla sulama pompalarını gün boyu çalıştırarak maliyetsiz sulama sağlıyor. 2,5 yılda yatırım amortismanı.',
 '/images/placeholder-project-3-before.svg', '/images/placeholder-project-3-after.svg',
 array['/images/placeholder-project-3-1.svg','/images/placeholder-project-3-2.svg'],
 array[]::text[],
 'Sulama maliyetimiz neredeyse sıfırlandı.', 'Söke Çiftçi Birliği', 195000, '2024-07-20', 90),
('sanliurfa-pompa', 'Şanlıurfa Tarımsal Pompaj', 'tarim', 'Şanlıurfa / Harran', 50, '/images/placeholder-project-6.svg',
 '50 kWp pompaj sistemi. GAP bölgesinin yüksek güneşlenmesinden faydalanan bu sistem, 80 hektarlık tarım arazisinin sulamasını üstleniyor.',
 null, null,
 array['/images/placeholder-project-6-1.svg'],
 array[]::text[],
 null, null, 360000, '2024-10-08', 100),
('mersin-sera', 'Mersin Hibrit Sera', 'tarim', 'Mersin / Tarsus', 75, '/images/placeholder-project-11.svg',
 '75 kWp hibrit batarya destekli sera projesi. Geceleri seranın iklim kontrolü batarya destekli sürdürülüyor.',
 null, null,
 array['/images/placeholder-project-11-1.svg','/images/placeholder-project-11-2.svg'],
 array[]::text[],
 'Yaz aylarında ürün kalitesi %18 arttı.', 'Tarsus Tarım Koop.', 540000, '2025-01-25', 110),
('manisa-bagcilik', 'Manisa Bağcılık Tesisi', 'tarim', 'Manisa / Salihli', 40, '/images/placeholder-project-12.svg',
 '40 kWp bağcılık işletmesi. Üzüm depolama soğuk hava deposunun yıllık enerji ihtiyacının %78''ini karşılıyor.',
 '/images/placeholder-project-12-before.svg', '/images/placeholder-project-12-after.svg',
 array['/images/placeholder-project-12-1.svg'],
 array[]::text[],
 null, null, 280000, '2025-04-02', 120);
